<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rkw_quickcheck"
 *
 * Auto generated by Extension Builder 2017-09-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'RKW QuickCheck',
    'description' => 'An Extension to manage answers of dichtiomous questions and returns a answer-based calculated result',
    'category' => 'plugin',
    'author' => 'Maximilian Fäßler',
    'author_email' => 'maximilian@faesslerweb.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '7.6.2',
    'constraints' => [
        'depends' => [
            'extbase' => '6.2.0-7.6.99',
            'fluid' => '6.2.0-7.6.99',
            'typo3' => '6.2.0-7.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
